### ISSUE TITLE
`No module named rasa_dc` when following 'native' setup instructions

### ISSUE THREAD

**Issue by svenvanderburg** [khalo-sa/rasa-apple-silicon#3]
When following these instructions: https://github.com/khalo-sa/rasa-apple-silicon#native-installation

When running command: `python -m rasa_dc --platform native --rasa_version $RASA_VERSION` I get:

```
No module named rasa_dc
```

**Comment by khalo-sa** [comment]
Hey @svenvanderburg , you are right, I forgot to document that you first have to install the dependency converter before using it. Can you try again with the updated documentation?

**Comment by svenvanderburg** [comment]
@khalo-sa now at the step: 
```
python -m rasa_dc --platform native --rasa_version $RASA_VERSION
```
I get:
```
Complex version constraints are not supported at the moment.
```

**Comment by khalo-sa** [comment]
That's okay, it's just a warning. Did you try the following steps?

**Comment by svenvanderburg** [comment]
Ah, OK. Yes it works! Thanks 👍  It would maybe be nice to document that the warning is expected.

**Comment by khalo-sa** [comment]
yeah, or just get rid of the warning. I'll take care of it soon
